### ISSUE TITLE
Mob Essence not dropping on server

### ISSUE THREAD

**Issue by ExaviorXY** [CAD97/SpawnerCraft#5]
I have made a 1.10 pack and neither the 1.9.4 or the 1.10 version seems to allow mobs to drop their essance when i kill them with the mob fishing rod. Any ideas? The current mod list is attached.
![mod list](https://cloud.githubusercontent.com/assets/20525622/16932298/9a60487e-4d13-11e6-9f8d-859be31bf768.png)

**Comment by ExaviorXY** [comment]
I am also using forge version 1.10.2-12.18.1.2014 but it hasnt worked with any of the 1.10.2 forges

**Comment by CAD97** [comment]
Thanks for reminding me to look into this; I've found the issue. I'm working on a patch right now.

For technical people (and my own reference): Here's the server stacktrace:

```
[18:24:20] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDropsEvent@4e747a98:
java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.applyEntityIdToItemStack(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
    at cad97.spawnercraft.handler.DropsListener.onMobDrops(DropsListener.java:71) ~[DropsListener.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_DropsListener_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:512) [ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1197) [EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1066) [EntityLivingBase.class:?]
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(EntityAnimal.java:80) [EntityAnimal.class:?]
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1388) [EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1374) [EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1090) [NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:93) [CPacketUseEntity.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:14) [CPacketUseEntity.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:25) [Util.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:742) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:408) [DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[18:24:20] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[18:24:20] [Server thread/ERROR] [FML]: 0: NORMAL
[18:24:20] [Server thread/ERROR] [FML]: 1: ASM: cad97.spawnercraft.handler.DropsListener@6b274b9c onMobDrops(Lnet/minecraftforge/event/entity/living/LivingDropsEvent;)V
[18:24:20] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.applyEntityIdToItemStack(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:26) [Util.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:742) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:408) [DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.applyEntityIdToItemStack(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
    at cad97.spawnercraft.handler.DropsListener.onMobDrops(DropsListener.java:71) ~[DropsListener.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_DropsListener_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:512) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1197) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1066) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(EntityAnimal.java:80) ~[EntityAnimal.class:?]
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1388) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1374) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1090) ~[NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:93) ~[CPacketUseEntity.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:14) ~[CPacketUseEntity.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
    ... 5 more
[18:24:31] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDropsEvent@7443ab05:
java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.applyEntityIdToItemStack(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
    at cad97.spawnercraft.handler.DropsListener.onMobDrops(DropsListener.java:71) ~[DropsListener.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_DropsListener_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:512) [ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1197) [EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1066) [EntityLivingBase.class:?]
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(EntityAnimal.java:80) [EntityAnimal.class:?]
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1388) [EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1374) [EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1090) [NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:93) [CPacketUseEntity.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:14) [CPacketUseEntity.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:25) [Util.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:742) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:408) [DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[18:24:31] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[18:24:31] [Server thread/ERROR] [FML]: 0: NORMAL
[18:24:31] [Server thread/ERROR] [FML]: 1: ASM: cad97.spawnercraft.handler.DropsListener@6b274b9c onMobDrops(Lnet/minecraftforge/event/entity/living/LivingDropsEvent;)V
[18:24:31] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.applyEntityIdToItemStack(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:26) [Util.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:742) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:408) [DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemMonsterPlacer.applyEntityIdToItemStack(Lnet/minecraft/item/ItemStack;Ljava/lang/String;)V
    at cad97.spawnercraft.handler.DropsListener.onMobDrops(DropsListener.java:71) ~[DropsListener.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_DropsListener_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:512) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1197) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1066) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(EntityAnimal.java:80) ~[EntityAnimal.class:?]
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1388) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1374) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1090) ~[NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:93) ~[CPacketUseEntity.class:?]
    at net.minecraft.network.play.client.CPacketUseEntity.processPacket(CPacketUseEntity.java:14) ~[CPacketUseEntity.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
    at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
    ... 5 more
```

**Comment by CAD97** [comment]
Specifically, I failed to honor `@SideOnly(Side.CLENT)` on `ItemMonsterPlacer::applyEntityIdToItemStack`

**Comment by ExaviorXY** [comment]
oh XD thats funny. Thanks for the support though

**Comment by CAD97** [comment]
I'll push a build out in a bit; I want to add #3, as that shouldn't be much work, and I need to pull the work into the 1.9 branch, but master now has the fix.

**Comment by CAD97** [comment]
Version 3.2 is out with the fix to this issue. http://minecraft.curseforge.com/projects/spawnercraft/files

**Comment by Diablillowilly** [comment]
The bug is alive again in the spawnercraft 1.11.2    4.0.0  with servers :(

**Comment by CAD97** [comment]
@Diablilowilly, can you post the stack trace from the server? That'll help me fix this quicker this weekend. I apologize for letting this in again, testing hasn't been up to par for the 4.0.0 beta releases.

**Comment by CAD97** [comment]
(I really should just test with the dedicated server and client instead of singleplayer worlds it seems...)

I've got a bit of time to work on this now.

Confirmed that it works fine in 1.12-4.0.0b2.
Confirmed that it works fine in 1.11.2-4.0.0b3.

What version are you using? I downloaded the jar and ran that, and it worked fine. Make sure you try it on vanilla mobs first. It only works on mobs with spawn eggs registered through the spawn egg registry.

**Comment by CAD97** [comment]
@Diablillowilly I'm going to close this issue. If the issue persists on your side, please open a new issue with a description of how to reproduce the issue. If `spawnercraft` appears in the server log, those lines are also relevant and could help me track down, reproduce, and fix the issue.

**Comment by Diablillowilly** [comment]
Your mod works perfectly, It wasn't working because I had a mod for having plugins in the server called sponge forge (spongeforge-1.11.2-2393-6.1.0-BETA-2484), and idk why or how, when I took it out the mobs started to drop essences, there has to be a conflict somewhere. (In the server log didn't appear any spawnercraft lines save for startup ones)
